// Service worker — hand-written so page navigations can NEVER hard-fail.
//
// Why this file exists at all (it used to be generated by vite-plugin-pwa's `generateSW`):
// the generated worker registered exactly one navigation route,
// `NavigationRoute(createHandlerBoundToURL('index.html'))`, with no catch handler. That route
// intercepts every top-level navigation — including a pull-to-refresh on a phone. Workbox's
// precache strategy falls back to the network when the precached `index.html` is missing (the
// browser evicts Cache Storage under storage pressure while leaving the registration intact), so
// a device in that state depends entirely on that network fetch. When it fails, the handler
// rejects, `event.respondWith()` receives a rejected promise, and the browser renders
// ERR_FAILED — "Nepavyksta pasiekti šios svetainės". The app looks *dead*, not offline, and every
// refresh repeats it because the same worker keeps intercepting.
//
// So the contract here is: a navigation always resolves with *something*. Precache first (instant,
// works offline), network second, and a plain offline page last — plus a worker update nudge, so
// a wiped precache repairs itself instead of stranding the device.

import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';

// `registerType: 'prompt'` means a new worker waits until the user accepts the in-app update
// (PwaUpdatePrompt) or presses the forced-update button (utils/appUpdate.js). Both signal through
// this message; without it a downloaded build would sit in `waiting` forever.
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// The last-resort document. Served from the worker's own script rather than a cached file, because
// the whole point is to survive the case where the cache is what went missing.
const OFFLINE_DOCUMENT = `<!doctype html>
<html lang="lt">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Gildija</title>
<style>
  body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center;
         background:#ffffff; color:#1f2937; font-family:system-ui,-apple-system,sans-serif; padding:24px; }
  main { max-width:22rem; text-align:center; }
  h1 { font-size:1.25rem; margin:0 0 .5rem; }
  p { font-size:.95rem; line-height:1.5; color:#4b5563; margin:0 0 1.5rem; }
  button { min-height:44px; width:100%; padding:0 1.25rem; border:0; border-radius:.75rem;
           background:#1f2937; color:#fff; font-size:1rem; font-weight:600; cursor:pointer; }
</style>
</head>
<body>
<main>
  <h1>Nepavyko įkelti programos</h1>
  <p>Patikrinkite interneto ryšį ir bandykite dar kartą. Jūsų įrašytas darbo laikas neprarastas.</p>
  <button type="button" onclick="location.reload()">Bandyti dar kartą</button>
</main>
</body>
</html>`;

const precachedIndex = createHandlerBoundToURL('index.html');

registerRoute(
    new NavigationRoute(async (options) => {
        try {
            return await precachedIndex(options);
        } catch {
            // Both the precache and its network fallback failed. Ask the browser to re-fetch the
            // worker script: a fresh install repopulates the precache, so the device heals on the
            // next attempt instead of being stuck behind a broken cache forever.
            self.registration.update().catch(() => undefined);

            return new Response(OFFLINE_DOCUMENT, {
                status: 200,
                headers: { 'Content-Type': 'text/html; charset=utf-8' },
            });
        }
    })
);
